A non-functional checking updating to hdf5-1.8.8 and szip-2.1. (issue #1).

diff --git a/src/hdf5/examples/testh5cc.sh.in b/src/hdf5/examples/testh5cc.sh.in
--- a/src/hdf5/examples/testh5cc.sh.in
+++ b/src/hdf5/examples/testh5cc.sh.in
@@ -14,16 +14,23 @@
 # access to either file, you may request a copy from help@hdfgroup.org.
 #
 # Tests for the h5cc compiler tool
-# Created: Albert Cheng, 2007/3/13
+# Created: Albert Cheng, 2007/4/11
 #
 # Modification:
-#	Albert Cheng, 2007/4/13
+#	Albert Cheng, 2008/9/27
 #	Added -shlib tests and verbose control.
+#	Albert Cheng, 2009/10/28
+#	Added version compatibility tests.
 #
 
 # Initializations
+TESTNAME=h5cc
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 # Where the tool is installed.
-prefix="${prefix:-@prefix@}"
+# Note: no '/' after DESTDIR.  Explanation in commence.am
+prefix="${prefix:-${DESTDIR}@prefix@}"
 PARALLEL=@PARALLEL@		# Am I in parallel mode?
 AR="@AR@"
 RANLIB="@RANLIB@"
@@ -37,9 +44,11 @@ H5TOOL_BIN="${prefix}/bin/${H5TOOL}"   # The path of the tool binary
 CMP='cmp -s'
 DIFF='diff -c'
 
-nerrors=0
+nerrors=$EXIT_SUCCESS
 verbose=${HDF5_VERBOSE:-1}      # 0: none; 1: default; 2: chatty; 3: everything
 test $verbose -gt 2 && set -x
+H5_NO_DEPRECATED_SYMBOLS=`grep '#define H5_NO_DEPRECATED_SYMBOLS ' ../src/H5pubconf.h`
+H5_USE_16_API_DEFAULT=`grep '#define H5_USE_16_API_DEFAULT ' ../src/H5pubconf.h`
 
 # setup my machine information.
 myos=`uname -s`
@@ -54,6 +63,10 @@ fi
 suffix=c		# source file suffix
 hdf5main=${H5TOOL}_hdf5main.$suffix
 hdf5main_o=${H5TOOL}_hdf5main.o
+v16main=${H5TOOL}_v16main.$suffix
+v16main_o=${H5TOOL}_v16main.o
+v18main=${H5TOOL}_v18main.$suffix
+v18main_o=${H5TOOL}_v18main.o
 appmain=${H5TOOL}_appmain.$suffix
 appmain_o=${H5TOOL}_appmain.o
 prog1=${H5TOOL}_prog1.$suffix
@@ -67,7 +80,7 @@ applib=libapp${H5TOOL}.a
 # Don't use the wildcard form of *.h5 as it will wipe out even *.h5 generated
 # by otehr test programs. This will cause a racing condition error when
 # parallel make (e.g., gmake -j 4) is used.
-temp_SRC="$hdf5main $appmain $prog1 $prog2"
+temp_SRC="$hdf5main $v16main $v18main $appmain $prog1 $prog2"
 temp_OBJ=`echo $temp_SRC | sed -e "s/\.${suffix}/.o/g"`
 temp_FILES="a.out $applib"
 
@@ -134,9 +147,59 @@ main (void)
 
     printf("HDF5 C Sample program ran successfully. File %s generated.\n", H5FILE_NAME);
     remove(H5FILE_NAME);
- 
+
     return 0;
 }     
+EOF
+
+# Generate HDF5 v1.6 Main Program:
+# This makes unique V1.6 API calls.
+cat > $v16main <<EOF
+/* This is a V1.6 API calls example Program. */
+#include "hdf5.h"
+#define H5FILE_NAME        "tmp.h5"
+int
+main (void)
+{
+    hid_t       file, group, group1;    /* file and group handles */
+
+    file = H5Fcreate(H5FILE_NAME, H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);
+    group = H5Gcreate(file, "/Group", 0);
+    group1 = H5Gcreate1(file, "/Group1.6", 0);
+    H5Gclose(group1);
+    H5Gclose(group);
+    H5Fclose(file);
+
+    printf("HDF5 C program created with V1.6 API ran successfully. "
+       "File %s generated.\n", H5FILE_NAME);
+    remove(H5FILE_NAME);
+    return 0;
+}
+EOF
+
+# Generate HDF5 v1.8 Main Program:
+# This makes unique V1.8 API calls.
+cat > $v18main <<EOF
+/* This is a V1.8 API calls example Program. */
+#include "hdf5.h"
+#define H5FILE_NAME        "tmp.h5"
+int
+main (void)
+{
+    hid_t       file, group, group2;    /* file and group handles */
+
+    file = H5Fcreate(H5FILE_NAME, H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);
+    group = H5Gcreate(file, "/Group", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
+    group2 = H5Gcreate2(file, "/Group1.8", H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
+    H5Gclose(group2);
+    H5Gclose(group);
+    H5Fclose(file);
+
+    printf("HDF5 C program created with V1.8 API ran successfully. "
+       "File %s generated.\n", H5FILE_NAME);
+    remove(H5FILE_NAME);
+    return 0;
+}
 EOF
 
 
@@ -245,6 +308,36 @@ echo "***"Just preprocess, no compile, no link.
 TOOLTEST -E $hdf5main
 TOOLTEST -E $appmain $prog1 $prog2
 
+# Group5: Version compatibility tests.
+echo "***"Version compatibility tests.
+# Test these two cases now. More later.
+# If H5_NO_DEPRECATED_SYMBOLS;
+# then only v18main works.
+# else if H5_USE_16_API_DEFAULT;
+#      then v16main works and -DH5_NO_DEPRECATED_SYMBOLS v18main also works.
+#      else v18main works and -DH5_USE_16_API_DEFAULT v16main also works.
+#
+if [ -n "$H5_USE_16_API_DEFAULT" ]; then
+    echo "H5_USE_16_API_DEFAULT is defined."
+else
+    echo "H5_USE_16_API_DEFAULT is not defined."
+fi
+if [ -n "$H5_NO_DEPRECATED_SYMBOLS" ]; then
+    echo "H5_NO_DEPRECATED_SYMBOLS is defined."
+else
+    echo "H5_NO_DEPRECATED_SYMBOLS is not defined."
+fi
+if [ -n "$H5_NO_DEPRECATED_SYMBOLS" ]; then
+    echo "Skipping $v16main test"
+    TOOLTEST $v18main
+elif [ -n "$H5_USE_16_API_DEFAULT" ]; then
+    TOOLTEST $v16main
+    TOOLTEST -DH5_NO_DEPRECATED_SYMBOLS $v18main
+else
+    TOOLTEST -DH5_USE_16_API_DEFAULT $v16main
+    TOOLTEST $v18main
+fi
+
 ##############################################################################
 # END
 ##############################################################################
@@ -255,7 +348,9 @@ if test -z "$HDF5_NOCLEANUP"; then
 fi
 
 if test $nerrors -eq 0 ; then
-   echo "All $H5TOOL tests passed."
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
 fi
-
-exit $nerrors
diff --git a/src/hdf5/testpar/testph5.sh.in b/src/hdf5/testpar/testph5.sh.in
--- a/src/hdf5/testpar/testph5.sh.in
+++ b/src/hdf5/testpar/testph5.sh.in
@@ -1,5 +1,5 @@
 #! /bin/sh
-##
+#
 # Copyright by The HDF Group.
 # Copyright by the Board of Trustees of the University of Illinois.
 # All rights reserved.
@@ -12,7 +12,7 @@
 # is linked from the top-level documents page.  It can also be found at
 # http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have
 # access to either file, you may request a copy from help@hdfgroup.org.
-##
+#
 
 # Scripts for running testphdf5 program with a variety of parameters
 top_srcdir=@top_srcdir@
@@ -59,6 +59,17 @@ TOOLTEST() {
 
 # testphdf5 test using the MPI-POSIX VFL driver
 TOOLTEST -p
+
+# Temporary patch:
+# Run t_shapesame this way. Need more permanent solution.
+echo $RUNPARALLEL ./t_shapesame -p
+eval $RUNPARALLEL ./t_shapesame -p
+
+# Check if the command failed and increment nerrors if so.
+if test $? -ne 0 ; then
+    nerrors="`expr $nerrors + 1`"
+fi
+# Temporary patch ended.
 
 # Emit message about testing status
 if test $nerrors -eq 0 ; then
